image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -rp diapo public/
  - cp -rp tp* public/
  - cp index.html public/
  artifacts:
    paths:
    - public
  only:
  - master

